# Generated by Django 5.1.7 on 2025-03-24 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0002_imagemproduto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='imagem',
        ),
    ]
